apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: my-pipeline-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gittag
    description: The git tag
    default: latest
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: picalc-git-$(uid)
    spec:
      type: git
      params:
        - name: revision
          value: master
        - name: url
          value: https://github.com/zhanggbj/tekton-tutorial
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: picalc-pr-
    spec:
      pipelineRef:
        name: build-and-deploy-pipeline
      resources:
        - name: git-source
          resourceRef:
            name: picalc-git-$(uid)
      params:
        - name: pathToYamlFile
          value: "knative/picalc.yaml"
        - name: imageUrl
          value: us.icr.io/zhanggbj-cr/picalc
        - name: imageTag
          value: $(params.gittag)
      serviceAccount: pipeline-account

